import {GridModel} from '../grid/grid.model';
import {ViewModel} from '../view/view.model';
import {DataModel} from '../data/data.model';
import {HeadModel} from '../head/head.model';
import {BodyModel} from '../body/body.model';
import {LayoutModel} from '../layout/layout.model';
import {NavigationModel} from '../navigation/navigation.model';
import {FocusModel} from '../focus/focus.model';
import {ColumnListModel} from '../column-list/column.list.model';
import {RowModel} from '../row/row.model';
import {SelectionModel} from '../selection/selection.model';
import {FootModel} from '../foot/foot.model';
import {SortModel} from '../sort/sort.model';
import {GroupModel} from '../group/group.model';
import {PivotModel} from '../pivot/pivot.model';
import {PluginModel} from '../plugin/plugin.model';
import {EditModel} from '../edit/edit.model';
import {ToolbarModel} from '../toolbar/toolbar.model';
import {LayerModel} from '../layer/layer.model';
import {PaginationModel} from '../pagination/pagination.model';
import {ProgressModel} from '../progress/progress.model';
import {HighlightModel} from '../highlight/highlight.model';
import {VisibilityModel} from '../visibility/visibility.model';
import {FilterModel} from '../filter/filter.model';
import {DragModel} from '../drag/drag.model';
import {StyleModel} from '../style/style.model';
import {ScrollModel} from '../scroll/scroll.model';
import {ExportModel} from '../export/export.model';
import {ActionModel} from '../action/action.model';
import {FetchModel} from '../fetch/fetch.model';

export declare class Model {
	constructor();
	static register(name: string, model: Model): Model;
	grid() : GridModel;
	edit(): EditModel;
	view(): ViewModel;
	data(): DataModel;
	head(): HeadModel;
	body(): BodyModel;
	layout(): LayoutModel;
	navigation(): NavigationModel;
	focus(): FocusModel;
	columnList(): ColumnListModel;
	row(): RowModel;
	selection(): SelectionModel;
	foot(): FootModel;
	sort(): SortModel;
	group(): GroupModel;
	pivot(): PivotModel;
	plugin(): PluginModel;
	toolbar(): ToolbarModel;
	layer(): LayerModel;
	pagination(): PaginationModel;
	progress(): ProgressModel;
	highlight(): HighlightModel;
	visibility(): VisibilityModel;
	filter(): FilterModel;
	drag(): DragModel;
	style(): StyleModel;
	scroll(): ScrollModel;
	export(): ExportModel;
	action(): ActionModel;
	fetch(): FetchModel;
}